//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyWebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Car
    {
        public Car()
        {
            this.Contracts = new HashSet<Contract>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Photo { get; set; }
        public bool Available { get; set; }
        public string Color { get; set; }
        public string Description { get; set; }
        public Nullable<int> Range { get; set; }
        public Nullable<int> Year { get; set; }
        public string Features { get; set; }
    
        public virtual ICollection<Contract> Contracts { get; set; }
    }
}
